theme:
  - osuny
  - osuny-plugin-centered-header
  - osuny-plugin-centered-layout
  - osuny-plugin-centered-footer
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo-blanc.svg'
  home:
    head:
      title: site